<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.1 on darwin)" generated="20210113 09:59:41.398" rpa="false">
<suite id="s1" name="Amazon" source="/Users/andrewwoltman/PycharmProjects/Amazon Search Test/tests/amazon.robot">
<test id="s1-t1" name="Logged out user can search for products">
<kw name="Begin Web Test" library="Common" type="setup">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>about:blank</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg timestamp="20210113 09:59:41.551" level="INFO">Opening browser 'chrome' to base url 'about:blank'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210113 09:59:41.554" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20210113 09:59:41.554" endtime="20210113 09:59:41.554"></status>
</kw>
<msg timestamp="20210113 09:59:41.556" level="FAIL">WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
</msg>
<status status="FAIL" starttime="20210113 09:59:41.551" endtime="20210113 09:59:41.556"></status>
</kw>
<status status="FAIL" starttime="20210113 09:59:41.551" endtime="20210113 09:59:41.556"></status>
</kw>
<kw name="End Web Test" library="Common" type="teardown">
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20210113 09:59:41.556" endtime="20210113 09:59:41.557"></status>
</kw>
<status status="PASS" starttime="20210113 09:59:41.556" endtime="20210113 09:59:41.557"></status>
</kw>
<tags>
<tag>Current</tag>
<tag>Search</tag>
</tags>
<status status="FAIL" starttime="20210113 09:59:41.550" endtime="20210113 09:59:41.557" critical="yes">Setup failed:
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
</status>
</test>
<doc>This is some basic info about the whole suite</doc>
<status status="FAIL" starttime="20210113 09:59:41.399" endtime="20210113 09:59:41.557"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">Current</stat>
<stat pass="0" fail="1">Search</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Amazon">Amazon</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210113 09:59:41.538" level="ERROR">Error in file '/Users/andrewwoltman/PycharmProjects/Amazon Search Test/Resources/PO/LandingPage.robot' on line 2: Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/andrewwoltman/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages</msg>
<msg timestamp="20210113 09:59:41.543" level="ERROR">Error in file '/Users/andrewwoltman/PycharmProjects/Amazon Search Test/Resources/PO/SearchResults.robot' on line 2: Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/andrewwoltman/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages</msg>
<msg timestamp="20210113 09:59:41.545" level="ERROR">Error in file '/Users/andrewwoltman/PycharmProjects/Amazon Search Test/Resources/PO/Product.robot' on line 2: Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/andrewwoltman/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages</msg>
<msg timestamp="20210113 09:59:41.547" level="ERROR">Error in file '/Users/andrewwoltman/PycharmProjects/Amazon Search Test/Resources/PO/Cart.robot' on line 2: Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/andrewwoltman/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages</msg>
<msg timestamp="20210113 09:59:41.549" level="ERROR">Error in file '/Users/andrewwoltman/PycharmProjects/Amazon Search Test/Resources/PO/SignIn.robot' on line 2: Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/andrewwoltman/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages</msg>
</errors>
</robot>
